[package]
name = "ordinal"
version = "0.1.0"
edition = "2021"
authors = ["Heath Stewart (https://github.com/heaths)"]
license = "MIT"
publish = false

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "ordinal"
harness = false
