[colors]
current_sample = { r = 149, g = 184, b = 209 }
previous_sample = { r = 128, g = 155, b = 206 }
comparison_colors = [
    { r = 0, g = 48, b = 73 },
    { r = 107, g = 44, b = 57 },
    { r = 214, g = 40, b = 40 },
    { r = 231, g = 84, b = 20 },
    { r = 247, g = 127, b = 0 },
    { r = 252, g = 191, b = 73 },
    { r = 243, g = 209, b = 128 },
    { r = 234, g = 226, b = 183 },
]
