[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
description = "Custom repository build tasks"
publish = false

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
xrust = "1.2.0"
