name: ci

on:
  pull_request:
  push:
    branches:
    - main
  workflow_call:

defaults:
  run:
    shell: bash

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
        include:
        - os: ubuntu-latest
          rust: stable
    steps:
    - &checkout
      name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - &cache
      name: Cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Set up toolchain
      run: rustup install --override ${{ matrix.rust }}
    - name: Test all features
      run: |
        cargo test --all-features --all-targets --workspace
        cargo test --all-features --doc --workspace
    - name: Test non-default features
      run: |
        cargo test --no-default-features --all-targets --workspace
        cargo test --no-default-features --features alloc --all-targets --workspace
        cargo test --no-default-features --doc --workspace

  analyze:
    runs-on: ubuntu-latest
    steps:
    - *checkout
    - *cache
    - name: Set up toolchain
      run: rustup install
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Lint
      run: |
        cargo clippy --all-features --all-targets --no-deps --workspace
        cargo clippy --no-default-features --all-targets --no-deps --workspace
    - name: Check spelling
      uses: streetsidesoftware/cspell-action@e0668cf020899e887ee8ad4d173c31738a79eae8 # v9.0.1
      with:
        config: .cspell.json
    - name: Build documentation
      run: cargo doc --all-features --no-deps --workspace
